### ISSUE TITLE
!oper no sirve :v

### ISSUE THREAD

**Issue by hendaniel** [GDAndres98/DiscordBot#3]
Pos nada ya es todo

**Comment by efbarong** [comment]
Manubrado

**Comment by hendaniel** [comment]
Cuando lo cierre tiene que poner el link del commit donde lo soluciono >:v @efbarong

**Comment by efbarong** [comment]
> Cuando lo cierre tiene que poner el link del commit donde lo soluciono >:v @efbarong

https://github.com/GDAndres98/DiscordBot/tree/3cf80d60b8b5bfca0a6079227da55214d9c17172 xddd
